'''
This is a setup.py script generated by py2applet

Usage:
    python BetterDict.setup.py py2app
'''

from setuptools import setup

def get_module_name(pkg_name):
  # some pip package names are different from module names
  pkg_to_module_map = {
    'beautifulsoup4': 'bs4'
  }
  return pkg_to_module_map.get(pkg_name, pkg_name)


def get_requirements():
  with open('requirements.txt') as f:
    return [
      get_module_name(l.split('==')[0])
      for l in f.readlines()
      if not l.startswith('py2app')
    ]


APP = ['BetterDict.py']
DATA_FILES = [
  'cocoadialog.app',
  'dict-entry.css',
]
OPTIONS = {
  'argv_emulation': True,
  'iconfile': 'dictionary.icns',
  # No idea why these are being included by default!
  'excludes': ['PIL', 'numpy', 'scipy', 'matplotlib'],
  'packages': get_requirements(),
  'plist': {
    'LSUIElement': True,
  },
}

setup(
  app=APP,
  data_files=DATA_FILES,
  options={'py2app': OPTIONS},
  py_modules=['alfred', 'ProgressBar', 'WorkflowGraph'],
  setup_requires=['py2app'],
)
